Repository BoardSignal/Team-CivilWar-BoardSignal-BE, pull requests merged in 2024-02, with the labels that each got.

#5 fix : 기존 인증, 엔티티 베이스 코드 버그 픽스
  .github/workflows/ci.yml
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/auth/filter/CustomAuthenticationFilter.java
  api/src/test/resources/application.yml
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/auth/infrastructure/JwtTokenProvider.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGameCategory.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/ReviewEvaluation.java
  core/src/testFixtures/java/com/civilwar/boardsignal/support/DatabaseCleaner.java
  core/src/testFixtures/java/com/civilwar/boardsignal/support/DatabaseCleanerExtension.java
Labels: Fix

#8 feat : 회원 가입 api
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/user/dto/request/ApiUserJoinRequest.java
  api/src/main/java/com/civilwar/boardsignal/user/mapper/UserApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  api/src/test/resources/testFile.png
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/constant/Category.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/image/domain/ImageRepository.java
  core/src/main/java/com/civilwar/boardsignal/image/infrastructure/S3ImageRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/constants/AgeGroup.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/constants/Gender.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/UserCategory.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/request/UserJoinRequest.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserJoinResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/exception/UserErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
  core/src/test/java/com/civilwar/boardsignal/user/application/UserServiceTest.java
  core/src/test/resources/testFile.png
  core/src/testFixtures/java/com/civilwar/boardsignal/common/MultipartFileFixture.java
  core/src/testFixtures/java/com/civilwar/boardsignal/user/UserFixture.java
Labels: Feat

#10 feat : 보드게임 필터링 통한 전체조회 API 구현
  .github/workflows/ci.yml
  .gitignore
  api/build.gradle
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/constant/Category.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/constant/Difficulty.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGame.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGameCategory.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/BoardGameQueryRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/BoardGameRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/BoardGameMapper.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/request/BoardGameSearchCondition.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/BoardGamePageResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/GetAllBoardGamesResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/BoardGameJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/common/configuratrion/QueryDslConfig.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
  core/src/test/java/com/civilwar/boardsignal/common/support/DataJpaTestSupport.java
  core/src/test/resources/application.yml
  core/src/testFixtures/java/com/civilwar/boardsignal/fixture/BoardGameFixture.java
Labels: Feat

#11 feat : 사용자는 소셜 로그인을 할 수 있다
  .github/workflows/ci.yml
  .gitignore
  api/src/main/java/com/civilwar/boardsignal/ApiApplication.java
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/auth/dto/OAuthUserInfo.java
  api/src/main/java/com/civilwar/boardsignal/auth/dto/request/ApiIssueTokenRequest.java
  api/src/main/java/com/civilwar/boardsignal/auth/dto/response/ApiUserLoginResponse.java
  api/src/main/java/com/civilwar/boardsignal/auth/handler/OAuth2LoginSuccessHandler.java
  api/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/auth/mapper/OAuthAttributeMapper.java
  api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java
  api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/auth/application/AuthService.java
  core/src/main/java/com/civilwar/boardsignal/auth/domain/RefreshTokenRepository.java
  core/src/main/java/com/civilwar/boardsignal/auth/domain/TokenProvider.java
  core/src/main/java/com/civilwar/boardsignal/auth/domain/model/Token.java
  core/src/main/java/com/civilwar/boardsignal/auth/dto/request/UserLoginRequest.java
  core/src/main/java/com/civilwar/boardsignal/auth/dto/response/IssueTokenResponse.java
  core/src/main/java/com/civilwar/boardsignal/auth/dto/response/UserLoginResponse.java
  core/src/main/java/com/civilwar/boardsignal/auth/infrastructure/JwtTokenProvider.java
  core/src/main/java/com/civilwar/boardsignal/auth/infrastructure/RefreshTokenRedisRepository.java
  core/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthMapper.java
  core/src/main/java/com/civilwar/boardsignal/auth/properties/JwtProperty.java
  core/src/main/java/com/civilwar/boardsignal/common/config/RedisConfig.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/constants/AgeGroup.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/constants/Gender.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/constants/OAuthProvider.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/UserCategory.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/auth/application/AuthServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/auth/infrastructure/JwtTokenProviderTest.java
  core/src/test/java/com/civilwar/boardsignal/auth/infrastructure/RefreshTokenRedisRepositoryTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/support/TestContainerSupport.java
  core/src/testFixtures/java/com/civilwar/boardsignal/user/UserFixture.java
Labels: Feat

#12 feat : 방 생성 API 구현
  .github/workflows/ci.yml
  api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiCreateRoomRequest.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/common/support/ApiTestSupport.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/constants/DaySlot.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/constants/TimeSlot.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Participant.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomCategory.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/request/CreateRoomResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/CreateRoomRequest.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Feat

#13 edit : 회원가입 API -> 사용자 정보 수정 API
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/user/dto/request/ApiUserJoinRequest.java
  api/src/main/java/com/civilwar/boardsignal/user/dto/request/ApiUserModifyRequest.java
  api/src/main/java/com/civilwar/boardsignal/user/mapper/UserApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/common/support/ApiTestSupport.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGame.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGameCategory.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/BoardGamePageResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/constants/DaySlot.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Participant.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomCategory.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/request/UserModifyRequest.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserModifyResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/exception/UserErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
  core/src/test/java/com/civilwar/boardsignal/user/application/UserServiceTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/support/TestContainerSupport.java
Labels: Edit

#14 feat : 로그아웃 API 구현
  api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java
  api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/auth/application/AuthService.java
  core/src/main/java/com/civilwar/boardsignal/auth/domain/RefreshTokenRepository.java
  core/src/main/java/com/civilwar/boardsignal/auth/domain/TokenProvider.java
  core/src/main/java/com/civilwar/boardsignal/auth/dto/response/UserLogoutResponse.java
  core/src/main/java/com/civilwar/boardsignal/auth/infrastructure/JwtTokenProvider.java
  core/src/main/java/com/civilwar/boardsignal/auth/infrastructure/RefreshTokenRedisRepository.java
  core/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthMapper.java
  core/src/test/java/com/civilwar/boardsignal/auth/infrastructure/RefreshTokenRedisRepositoryTest.java
Labels: Feat

#19 fix : 페이징 관련 버그 수정 및 페이징 반환타입 변경
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGame.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGameCategory.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/BoardGameQueryRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/BoardGameMapper.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/BoardGamePageResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
Labels: Fix

#23 feat : 보드게임 찜하기 API 구현
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/common/config/CorsConfig.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGame.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Wish.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/WishRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/WishBoardGameResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/WishRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/WishJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/fixture/BoardGameFixture.java
Labels: Feat

#27 feat : 공략 등록 API 구현
  api/src/main/java/com/civilwar/boardsignal/boardgame/dto/mapper/BoardGameApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/boardgame/dto/request/ApiAddTipRequest.java
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Tip.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/BoardGameMapper.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/request/AddTipRequest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/AddTipResposne.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/TipRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/TipJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/fixture/BoardGameFixture.java
Labels: Feat

#26 feat : 유저는 프로필을 조회할 수 있다.
  api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/constant/ReviewContent.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/Review.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/ReviewEvaluation.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/repository/ReviewRepository.java
  core/src/main/java/com/civilwar/boardsignal/review/infrastructure/adaptor/ReviewRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/UserCategory.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserProfileResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserReviewResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/facade/UserReviewFacade.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
  core/src/test/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepositoryTest.java
  core/src/test/java/com/civilwar/boardsignal/user/facade/UserReviewFacadeTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/review/ReviewFixture.java
Labels: Feat

#30 feat : 보드게임 상세정보 조회 API 구현
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Tip.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/BoardGameMapper.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/GetBoardGameResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/GetTipResposne.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/TipRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/TipJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/common/base/BaseEntity.java
  core/src/main/java/com/civilwar/boardsignal/common/config/AuditingConfig.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepositoryTest.java
  core/src/test/java/com/civilwar/boardsignal/user/domain/repository/UserRepositoryTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/fixture/BoardGameFixture.java
  core/src/testFixtures/java/com/civilwar/boardsignal/user/UserFixture.java
Labels: Feat

#32 feat : 보드게임 검색 기능 구현
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/request/BoardGameSearchCondition.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/ReviewEvaluation.java
  core/src/main/java/com/civilwar/boardsignal/user/facade/UserReviewFacade.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
Labels: Feat

#35 feat : 사용자는 참여했던 모임들을 조회할 수 있다
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/common/config/QueryDslConfig.java
  core/src/main/java/com/civilwar/boardsignal/common/config/TimeConfig.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/MeetingInfo.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomCategory.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetAllRoomResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/RoomPageResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/MeetingInfoJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/common/support/DataJpaTestSupport.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/MeetingInfoFixture.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Feat

#37 feat : 찜 등록에 대한 동시성 이슈 제어
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/BoardGameQueryRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/BoardGameJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameConcurrencyTest.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
Labels: Feat

#38 edit : 프로필 조회 시, 사용자의 찜 갯수도 보여준다
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/WishRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/WishRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/WishJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserProfileResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
Labels: Edit

#39 feat : 사용자는 방을 검색&필터링 조회할 수 있다.
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/request/RoomSearchCondition.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetAllRoomResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Feat

#40 feat : 방을 단일조회 할 수 있다.
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantJpaDto.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/RoomInfoResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantQueryJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepositoryTest.java
Labels: Feat

#44 feat : 좋아요 등록 및 취소 API 구현
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Like.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Tip.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/LikeRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/LikeTipResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/LikeRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/TipRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/LikeJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/TipJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/common/support/DataJpaTestSupport.java
  core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Feat

#55 feat : 공략 삭제 API 구현
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/TipRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/TipJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantResponse.java
  core/src/test/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepositoryTest.java
Labels: Feat

#53 edit : 프로필 조회 API 수정
  api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserProfileResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
Labels: Edit

#54 edit : 방 상세정보 조회 API 수정
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/RoomInfoResponse.java
Labels: Edit

#57 edit : 방 필터링 조회 API
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/request/RoomSearchCondition.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetAllRoomResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/RoomInfoResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/constants/Gender.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Edit

#61 feat : 사용자는 같이 게임에 참여한 사용자들을 리뷰할 수 있다
  api/src/main/java/com/civilwar/boardsignal/common/config/CorsConfig.java
  api/src/main/java/com/civilwar/boardsignal/review/dto/ApiReviewSaveRequest.java
  api/src/main/java/com/civilwar/boardsignal/review/presentation/ReviewController.java
  api/src/test/java/com/civilwar/boardsignal/review/presentation/ReviewControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/review/application/ReviewService.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/constant/ReviewContent.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/Review.java
  core/src/main/java/com/civilwar/boardsignal/review/dto/request/ReviewEvaluationDto.java
  core/src/main/java/com/civilwar/boardsignal/review/dto/request/ReviewSaveRequest.java
  core/src/main/java/com/civilwar/boardsignal/review/dto/response/ReviewSaveResponse.java
  core/src/main/java/com/civilwar/boardsignal/review/exception/ReviewErrorCode.java
  core/src/test/java/com/civilwar/boardsignal/review/application/ReviewServiceTest.java
Labels: Feat
