Repository BoardSignal/Team-CivilWar-BoardSignal-BE, pull requests merged in 2024-03, with the labels that each got.

#62 feat : 클라이언트는 현재 로그인한 유저의 정보를확인할 수 있다
  api/src/main/java/com/civilwar/boardsignal/auth/dto/response/LoginUserInfoResponse.java
  api/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java
  api/src/main/java/com/civilwar/boardsignal/review/presentation/ReviewController.java
  api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
Labels: Feat

#63 edit : 방 상세정보는 인증되지 않은 사용자들도 접근할 수 있다
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Edit

#64 feat : 알림 이벤트 구현
  .github/workflows/cd.yml
  .gitignore
  api/src/main/java/com/civilwar/boardsignal/notification/presentation/NotificationController.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiCreateRoomRequest.java
  api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/common/config/AsyncConfig.java
  core/src/main/java/com/civilwar/boardsignal/common/config/FcmConfig.java
  core/src/main/java/com/civilwar/boardsignal/notification/application/NotificationService.java
  core/src/main/java/com/civilwar/boardsignal/notification/domain/constant/NotificationContent.java
  core/src/main/java/com/civilwar/boardsignal/notification/domain/constant/NotificationStatus.java
  core/src/main/java/com/civilwar/boardsignal/notification/domain/entity/Notification.java
  core/src/main/java/com/civilwar/boardsignal/notification/domain/repository/NotificationRepository.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/request/CreateFcmTokenReequest.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/request/NotificationTestRequest.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/response/CreateFcmTokenResponse.java
  core/src/main/java/com/civilwar/boardsignal/notification/event/NotificationEventHandler.java
  core/src/main/java/com/civilwar/boardsignal/notification/infrastructure/adaptor/NotificationRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/notification/infrastructure/repository/NotificationJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/constants/Gender.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/UserFcmToken.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserFcmTokenRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserFcmTokenRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserFcmTokenJpaRepository.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Feat

#67 edit : 보드게임 상세 조회 시 찜 여부, 좋아요 여부 필드 추가
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/LikeRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/BoardGameMapper.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/GetBoardGameResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/GetTipResposne.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/LikeRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/LikeJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
Labels: Edit

#68 feat : 인증 관련
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/auth/filter/JwtExceptionHandlerFilter.java
  api/src/main/java/com/civilwar/boardsignal/auth/handler/CustomAuthenticationEntryPoint.java
  api/src/main/java/com/civilwar/boardsignal/auth/handler/OAuth2LoginSuccessHandler.java
  api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/auth/exception/AuthErrorCode.java
Labels: Feat

#69 feat : 찜 취소 API 구현
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/main/java/com/civilwar/boardsignal/common/config/CorsConfig.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/review/presentation/ReviewControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/CancelWishResposne.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/constant/ReviewContent.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/review/application/ReviewServiceTest.java
Labels: Feat

#75 edit : 현재 사용자의 정보 조회 시, 나이도 함께 반환한다.
  api/src/main/java/com/civilwar/boardsignal/auth/dto/response/LoginUserInfoResponse.java
  api/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java
  api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
Labels: Edit

#74 feat : 보드게임 찜 목록 조회 API 구현
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/constant/Category.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/constant/Difficulty.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/BoardGameQueryRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/WishRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/WishRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/BoardGameJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/WishJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/constants/DaySlot.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/constants/TimeSlot.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
Labels: Feat

#77 feat : 모임 확정 API 구현
  api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiFixRoomRequest.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/common/support/ApiTestSupport.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/constants/WeekDay.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/MeetingInfo.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/MeetingInfoRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/request/FixRoomRequest.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/FixRoomResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/MeetingInfoRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantQueryJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/MeetingInfoFixture.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Feat

#88 feat : 모임 확정 취소 API 구현
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/MeetingInfoRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/MeetingInfoRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantQueryJpaRepository.java
Labels: Feat

#92 feat : 종료된 게임의 다른 참여자 조회 API 구현
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/common/config/CorsConfig.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameUsersResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantJpaDto.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantQueryJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Feat

#95 feat : 사용자는 모임에 참여할 수 있다
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantRoomResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#99 feat : S3 이미지 업로드 및 URL 반환
  api/src/test/resources/application.yml
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/common/config/S3Config.java
  core/src/main/java/com/civilwar/boardsignal/image/infrastructure/S3ImageRepository.java
  core/src/test/resources/application.yml
Labels: Feat

#98 feat : 사용자는 자신이 참여한 모임에서 나갈 수 있다
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ExitRoomResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#103 fix : 테스트 버그 수정
  .github/workflows/ci.yml
  .gitignore
  api/src/main/java/com/civilwar/boardsignal/notification/presentation/NotificationController.java
  api/src/test/resources/application.yml
  core/src/main/java/com/civilwar/boardsignal/common/config/FcmConfig.java
  core/src/test/resources/application.yml
  gradlew
Labels: Fix

#101 feat : 방장은 참여자를 추방할 수 있다
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/common/config/S3Config.java
  core/src/main/java/com/civilwar/boardsignal/image/infrastructure/S3ImageRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/request/KickOutUserRequest.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#105 fix : 알림 테스트용 api 버그 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/notification/presentation/NotificationController.java
  core/build.gradle
  core/src/main/java/com/civilwar/boardsignal/notification/application/FcmService.java
Labels: Fix

#112 edit : 모임 확정 시 요일 필드 제거
  api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiFixRoomRequest.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/common/config/S3Config.java
  core/src/main/java/com/civilwar/boardsignal/image/infrastructure/S3ImageRepository.java
  core/src/main/java/com/civilwar/boardsignal/notification/application/FcmService.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/constants/WeekDay.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/MeetingInfo.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/request/FixRoomRequest.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameUsersResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/MeetingInfoFixture.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Edit

#114 feat : 닉네임이 중복인지 체크할 수 있다
  api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/request/ValidNicknameRequest.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/ValidNicknameResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserJpaRepository.java
Labels: Feat

#115 edit : 현재 사용자의 정보 조회 필드 추가 (이름, 출생연도)
  api/src/main/java/com/civilwar/boardsignal/auth/dto/response/LoginUserInfoResponse.java
  api/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java
Labels: Edit

#109 feat : 채팅을 전송할 수 있다.
  api/build.gradle
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/auth/filter/CustomAuthenticationFilter.java
  api/src/main/java/com/civilwar/boardsignal/auth/handler/CustomAuthenticationEntryPoint.java
  api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java
  api/src/main/java/com/civilwar/boardsignal/chat/dto/ApiChatMessageRequest.java
  api/src/main/java/com/civilwar/boardsignal/chat/handler/StompAuthenticationHandler.java
  api/src/main/java/com/civilwar/boardsignal/chat/handler/StompExceptionHandler.java
  api/src/main/java/com/civilwar/boardsignal/chat/mapper/ChatMessageApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/chat/presentation/ChatMessageController.java
  api/src/main/java/com/civilwar/boardsignal/common/config/CorsConfig.java
  api/src/main/java/com/civilwar/boardsignal/common/config/WebSocketConfig.java
  api/src/main/java/com/civilwar/boardsignal/common/presentation/HealthCheckController.java
  api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/chat/application/ChatMessageService.java
  core/src/main/java/com/civilwar/boardsignal/chat/domain/constant/MessageType.java
  core/src/main/java/com/civilwar/boardsignal/chat/domain/entity/ChatMessage.java
  core/src/main/java/com/civilwar/boardsignal/chat/domain/repository/ChatMessageRepository.java
  core/src/main/java/com/civilwar/boardsignal/chat/dto/request/ChatMessageRequest.java
  core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatMessageResponse.java
  core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/adaptor/ChatMessageRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/chat/mapper/ChatMessageMapper.java
  core/src/main/java/com/civilwar/boardsignal/image/infrastructure/S3ImageRepository.java
Labels: Feat

#116 feat : 여러명에 대한 알림 처리 & 기기 토큰 저장 로직 수정
  api/src/main/java/com/civilwar/boardsignal/notification/presentation/NotificationController.java
  core/src/main/java/com/civilwar/boardsignal/notification/application/FcmSender.java
  core/src/main/java/com/civilwar/boardsignal/notification/application/NotificationService.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/request/NotificationRequest.java
  core/src/main/java/com/civilwar/boardsignal/notification/event/NotificationEventHandler.java
  core/src/main/java/com/civilwar/boardsignal/notification/exception/NotificationErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserFcmTokenRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserFcmTokenRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserFcmTokenJpaRepository.java
Labels: Feat, Edit

#119 edit : 모임 확정 API 인원 수 필드 제거
  .github/workflows/cd.yml
  api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiFixRoomRequest.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/request/FixRoomRequest.java
  core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
Labels: Edit

#121 edit : 보드게임 관련 페이징 조회 수정
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/BoardGameMapper.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/BoardGamePageResponse.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/image/infrastructure/S3ImageRepository.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/mapper/NotificationMapper.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/response/NotificationPageResponse.java
  core/src/main/java/com/civilwar/boardsignal/notification/event/NotificationEventHandler.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
Labels: Edit

#122 feat : 모임 참가자는 모임 채팅 내역을 조회할 수 있다
  api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java
  api/src/main/java/com/civilwar/boardsignal/chat/presentation/ChatMessageController.java
  api/src/main/java/com/civilwar/boardsignal/chat/presentation/StompMessageController.java
  api/src/test/java/com/civilwar/boardsignal/chat/presentation/ChatMessageControllerTest.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/chat/application/ChatMessageService.java
  core/src/main/java/com/civilwar/boardsignal/chat/domain/entity/ChatMessage.java
  core/src/main/java/com/civilwar/boardsignal/chat/domain/repository/ChatMessageRepository.java
  core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatMessageDto.java
  core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatPageResponse.java
  core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/adaptor/ChatMessageRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/chat/mapper/ChatMessageMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepositoryTest.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#126 feat : 알림 전송 로직 반영
  api/src/main/java/com/civilwar/boardsignal/review/presentation/ReviewController.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/chat/presentation/ChatMessageControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/chat/application/ChatMessageService.java
  core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatPageResponse.java
  core/src/main/java/com/civilwar/boardsignal/common/config/AsyncConfig.java
  core/src/main/java/com/civilwar/boardsignal/notification/domain/entity/Notification.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/mapper/NotificationMapper.java
  core/src/main/java/com/civilwar/boardsignal/notification/dto/response/NotificationResponse.java
  core/src/main/java/com/civilwar/boardsignal/review/facade/ReviewFacade.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/DeleteRoomFacadeResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/facade/RoomFacade.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepositoryTest.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#128 edit : 응답 필드 수정
  api/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthApiMapper.java
  api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java
  api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/LoginUserInfoResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
Labels: Edit

#129 edit : 방 관련 API 페이징 수정
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/Review.java
  core/src/main/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
Labels: Edit

#132 edit : 수정 작업
  api/src/main/java/com/civilwar/boardsignal/chat/handler/StompAuthenticationHandler.java
  api/src/main/java/com/civilwar/boardsignal/chat/handler/StompExceptionHandler.java
  api/src/main/java/com/civilwar/boardsignal/chat/handler/StompLogHandler.java
  api/src/main/java/com/civilwar/boardsignal/common/config/WebSocketConfig.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/facade/RoomFacade.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Edit

#139 edit : 종료된 게임에 참여한 유저 조회 API 응답 필드 수정
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameUsersResponse.java
Labels: Edit

#140 feat : 리뷰 작성 시, mannerScore 증가
  api/src/main/java/com/civilwar/boardsignal/chat/handler/StompLogHandler.java
  api/src/main/java/com/civilwar/boardsignal/chat/presentation/ChatMessageController.java
  api/src/main/java/com/civilwar/boardsignal/chat/presentation/StompMessageController.java
  api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java
  api/src/test/java/com/civilwar/boardsignal/review/presentation/ReviewControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/common/config/AsyncConfig.java
  core/src/main/java/com/civilwar/boardsignal/review/application/ReviewService.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/Review.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
  core/src/test/java/com/civilwar/boardsignal/review/application/ReviewServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#141 edit : 응답 필드 수정
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameResponse.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java
Labels: Feat

#144 feat : 모임 확정 시 날짜 검증 추가
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#145 feat : 내가 이전에 참여한 모임 조회 시, 해당 모임에 리뷰 반영 여부를 함께 반환한다
  api/src/main/java/com/civilwar/boardsignal/auth/handler/OAuth2LoginSuccessHandler.java
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/review/application/ReviewService.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/repository/ReviewRepository.java
  core/src/main/java/com/civilwar/boardsignal/review/exception/ReviewErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/review/infrastructure/adaptor/ReviewRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java
  core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/dto/response/LoginUserInfoResponse.java
  core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
  core/src/test/java/com/civilwar/boardsignal/review/application/ReviewServiceTest.java
  core/src/test/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepositoryTest.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#149 feat : 블랙리스트 추가
  api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomBlackList.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomBlackListRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomBlackListRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomBlackListJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
Labels: Feat

#151 feat : 강퇴 시 사용될 메시지 타입 추가
  core/src/main/java/com/civilwar/boardsignal/chat/domain/constant/MessageType.java
Labels: Feat

#152 feat : 프로필 조회 시 signal 업데이트 된 결과 조회
  api/build.gradle
  api/src/main/java/com/civilwar/boardsignal/ApiApplication.java
  core/src/main/java/com/civilwar/boardsignal/common/config/AsyncConfig.java
  core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserRepository.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserJpaRepository.java
  core/src/test/java/com/civilwar/boardsignal/user/domain/repository/UserRepositoryTest.java
  scheduler/build.gradle
  scheduler/src/main/java/com/civilwar/boardsignal/common/config/SchedulerConfig.java
  scheduler/src/main/java/com/civilwar/boardsignal/user/scheduler/UserSignalScheduler.java
  settings.gradle
Labels: Feat

#156 fix : 알림 버그 수정
  api/src/test/java/com/civilwar/boardsignal/notification/presentation/NotificationControllerTest.java
  core/src/main/java/com/civilwar/boardsignal/notification/application/FcmSender.java
  core/src/main/java/com/civilwar/boardsignal/notification/event/NotificationEventHandler.java
  core/src/main/java/com/civilwar/boardsignal/notification/infrastructure/adaptor/NotificationRepositoryAdaptor.java
  core/src/main/java/com/civilwar/boardsignal/notification/infrastructure/repository/NotificationJpaRepository.java
  core/src/main/java/com/civilwar/boardsignal/room/facade/RoomFacade.java
Labels: Fix

#158 edit : BaseEntity 추가
  api/src/main/java/com/civilwar/boardsignal/auth/filter/CustomAuthenticationFilter.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Like.java
  core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Wish.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/Review.java
  core/src/main/java/com/civilwar/boardsignal/review/domain/entity/ReviewEvaluation.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/MeetingInfo.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomBlackList.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomCategory.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Schedule.java
  core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Subway.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/UserCategory.java
  core/src/main/java/com/civilwar/boardsignal/user/domain/entity/UserFcmToken.java
Labels: Edit
